server:
    error.include-message: always
    error.include-binding: errors:always
spring:
    # Jackson Configuration
#    jackson:
#        serialization.indent_output: true
    # Datasource Configuration
#    datasource:
#        name: MySQL RDBMS Database Connection
#        driver-class-name: com.mysql.jdbc.Driver
        #    driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/hex_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
 #       username: root
#        password: root
        # Hikari CP Configuration
 #       hikari:
 #           data-source-properties:
#                cachePrepStmts: true
#                prepStmtCacheSize: 250
#                prepStmtCacheSqlLimit: 2048
#                useServerPrepStmts: true
    # Java Persistence API Configuration
 #   jpa:
#        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
#        database: MYSQL
#        show-sql: true
#        open-in-view: false
#        # Hibernate Properties
#        properties:
#            hibernate.cache.use_second_level_cache: false
#            hibernate.cache.use_query_cache: false
#            hibernate.generate_statistics: false
#            hibernate.show_sql: true
#            hibernate.SQL: true

    h2.console.enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
    data.jpa.repositories.bootstrap-mode: default
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    mvc.throw-exception-if-no-handler-found: true
    output.ansi.enabled: ALWAYS
logging:
    file:
        name: MyApp.log
        max-size: 1MB
        total-size-cap: 10MB
    pattern.rolling-file-name: MyApp-%d{yyyy-MM-dd}.%i.log
